version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id,
            description: order identifier and primary key
          - name: products_id,
            description: product identifier 
          - name: revenue,
            description: cost of purchase
          - name: quantity
            description: number of items purchased 
            tests:
             - unique:
               column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: product identifier and primary key
            tests:
              - unique
              - not_null 
          - name: purchase_price
            description: cost of each unique product and primary key
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: order_id
            description: product identifier 
          - name: shipping_fee
            description: price charged customer for each shipment 
          - name: log_cost
            description: logistics costs per shipment  
          - name: ship_cost
            description: cost of each shipment 
            tests:
              - unique:
                 column_name: order_id

